# Generated by Django 4.2.10 on 2024-12-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_orders_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_payment',
            field=models.CharField(default='Card', max_length=200),
        ),
    ]
