# Generated by Django 4.2.10 on 2024-12-15 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255)),
                ('vehicle_range', models.CharField(max_length=10)),
                ('vehicle_topspeed', models.CharField(max_length=10)),
                ('vehicle_acceleration', models.CharField(max_length=10)),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_home_image', models.URLField()),
                ('vehicle_image_1', models.URLField()),
                ('vehicle_image_1_name', models.CharField(max_length=100)),
                ('vehicle_image_2', models.URLField()),
                ('vehicle_image_2_name', models.CharField(max_length=100)),
                ('vehicle_image_3', models.URLField()),
                ('vehicle_image_3_name', models.CharField(max_length=100)),
                ('vehicle_image_4', models.URLField()),
                ('vehicle_image_4_name', models.CharField(max_length=100)),
                ('vehicle_wheel_1_image', models.URLField()),
                ('vehicle_wheel_1_name', models.CharField(max_length=100)),
                ('vehicle_wheel_2_image', models.URLField()),
                ('vehicle_wheel_2_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_custom_wheels', models.CharField(max_length=255)),
                ('vehicle_custom_color', models.CharField(max_length=255)),
                ('vehicle_custom_interior', models.CharField(max_length=255)),
                ('vehicle_custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_custom_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
